Repository FRONT-END-BOOTCAMP-PLUS-5/citychat, pull requests merged in 2025-07, with the labels that each got.

#7 Feature/add root layout
  app/(group)/layout.tsx
  app/components/Footer.tsx
  app/components/Header.tsx
  app/components/Slider.tsx
  app/components/footer.css
  app/components/header.css
  app/components/slider.css
  app/globals.css
  app/layout.tsx
  app/page.tsx
  next.config.ts
  package-lock.json
  package.json
  public/assets/background.jpg
  public/assets/github.png
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
Labels: enhancement

#13 feat : 채팅 태그, 댓글 기능 생성
  app/(auth)/chatrooms/[id]/components/Chat.css
  app/(auth)/chatrooms/[id]/components/ChatInput.tsx
  app/(auth)/chatrooms/[id]/components/ChatLog.tsx
  app/(auth)/chatrooms/[id]/components/ChatReply.tsx
  app/(auth)/chatrooms/[id]/components/ParseTags.ts
  app/(auth)/chatrooms/[id]/page.tsx
  package-lock.json
  public/assets/CityChat.png
Labels: enhancement

#21 feat : 채팅 Supabase 연결 저장 조회 완료, 시간 표시
  README.md
  app/(auth)/chatrooms/[id]/components/ChatInput.tsx
  app/(auth)/chatrooms/[id]/components/ChatLog.tsx
  app/(auth)/chatrooms/[id]/components/ChatReply.tsx
  app/(auth)/chatrooms/[id]/page.tsx
  app/(auth)/chatrooms/[id]/types.ts
  package-lock.json
  package.json
  public/assets/CityChat.png
  socket-server/index.ts
  socket-server/package-lock.json
  socket-server/package.json
  socket-server/src/supabaseClient.ts
  socket-server/src/types.ts
Labels: enhancement

#25 chore: #19 TanStack Query 초기 설정 및 테스트
  app/components/QueryProvider.tsx
  app/layout.tsx
  package-lock.json
  package.json
Labels: enhancement

#26 style : 메인 페이지 스타일 변경
  app/components/Footer.tsx
  app/components/Header.tsx
  app/components/Slider.tsx
  app/components/SubSlider.tsx
  app/components/footer.module.css
  app/components/subSlider.module.css
  app/globals.css
  app/page.tsx
Labels: documentation

#29 feat: #28 로그인 기능 임시 구현
  app/(anon)/login/page.tsx
  app/SharedPageLayout.tsx
  app/api/auth/signin/route.ts
  app/apis/authApi.ts
  app/hooks/useSignin.ts
  app/shared-page-layout.css
  backend/application/signin/dtos/SigninDto.ts
  backend/application/signin/usecases/NSigninUsecase.ts
  backend/domain/entities/User.ts
  backend/domain/repositories/UserRepository.ts
  backend/infrastructure/repositories/SbUserRepository.ts
Labels: enhancement

#32 feat: #28 JWT 토큰 발급 구현
  app/(anon)/login/page.tsx
  app/api/auth/signin/route.ts
  app/hooks/useSignin.ts
  backend/application/signin/dtos/SigninDto.ts
  backend/application/signin/usecases/NSigninUsecase.ts
  backend/infrastructure/repositories/SbUserRepository.ts
  package-lock.json
  package.json
  utils/jwt/tokenManager.ts
Labels: enhancement

#35 feat : #15 #8 #30 댓글 UI 구현, 채팅 태그 스타일 적용 및 메시지 번역 기능 추가
  app/(auth)/chatrooms/[id]/components/ChatInput.tsx
  app/(auth)/chatrooms/[id]/components/ChatLog.tsx
  app/(auth)/chatrooms/[id]/components/ParseTags.ts
  app/api/translate/route.ts
  app/hooks/useSignin.ts
  app/stores/useUserStore.ts
  backend/application/signin/dtos/SigninDto.ts
  backend/application/signin/usecases/NSigninUsecase.ts
  package-lock.json
  package.json
Labels: enhancement

#39 feat : 채팅방 메시지 전송 로직 구현 및 Zustand로 유저 상태 유지
  app/(anon)/login/page.tsx
  app/(auth)/chatrooms/[id]/components/ChatReply.tsx
  app/(auth)/chatrooms/[id]/page.tsx
  app/(auth)/chatrooms/[id]/types.ts
  app/hooks/useSignin.ts
  app/stores/useUserStore.ts
  socket-server/index.ts
  socket-server/src/types.ts
Labels: bug, enhancement

#46 Feature/28 signin
  app/(anon)/login/page.module.css
  app/(anon)/login/page.tsx
  app/api/auth/signin/route.ts
  app/hooks/useSignin.ts
  backend/application/auth/dtos/SigninDto.ts
  backend/application/auth/usecases/SigninUsecase.ts
Labels: enhancement

#50 chore: eslint 파일 수정
  eslint.config.mjs
Labels: enhancement

#62 refactor: token 관련 util 파일명 변경
  backend/application/auth/usecases/SigninUsecase.ts
  utils/auth/tokenUtils.ts
Labels: enhancement

#63 fix : slider.module.css 전역 선택자 오류 수정
  app/(anon)/cities/layout.tsx
  app/(anon)/cities/page.tsx
  app/api/cities/route.ts
  app/api/weather/route.ts
  app/components/Slider.tsx
  app/components/SubSlider.tsx
  app/components/header.module.css
  app/components/slider.module.css
  package.json
  utils/auth/tokenUtils.ts
  utils/supabase/client.ts
  utils/supabase/server.ts
Labels: bug

#64 release : deploy v1.1
  app/(anon)/chatrooms/[id]/components/ChatInput.tsx
  app/(anon)/chatrooms/[id]/components/ChatLog.module.css
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/chatrooms/[id]/components/ChatReply.tsx
  app/(anon)/chatrooms/[id]/components/ParseTags.ts
  app/(anon)/chatrooms/[id]/page.tsx
  app/(anon)/chatrooms/[id]/types.ts
  app/(anon)/cities/layout.tsx
  app/(anon)/cities/page.tsx
  app/(anon)/me/page.module.css
  app/(anon)/me/page.tsx
  app/(anon)/signup/page.module.css
  app/api/cities/route.ts
  app/api/weather/route.ts
  app/components/Slider.tsx
  app/components/SubSlider.tsx
  app/components/header.module.css
  app/components/slider.module.css
  backend/application/auth/usecases/SigninUsecase.ts
  package.json
  utils/auth/tokenUtils.ts
  utils/supabase/client.ts
  utils/supabase/server.ts
Labels: bug

#65 release : v1.1.1
  package.json
Labels: bug

#67 release : v 1.1.2
  app/components/AuthGuard.tsx
  app/layout.tsx
  middleware.ts
  package.json
  tsconfig.json
  utils/auth/tokenUtils.ts
Labels: bug

#72 fix: #45 AuthGuard hydration 문제 해결
  app/components/AuthGuard.tsx
Labels: enhancement

#74 fix: #45 AuthGuard hydration 문제 해결
  app/components/AuthGuard.tsx
Labels: bug

#75 fix: #45 useEffect 의존성 배열 추가
  app/components/AuthGuard.tsx
Labels: bug

#77 refactor: #45 auth 관련 설정 변수들 config 파일 작성
  app/components/AuthGuard.tsx
  config/auth.ts
  middleware.ts
Labels: enhancement

#87 Feature/82 mypage
  app/(anon)/me/page.module.css
  app/(anon)/me/page.tsx
  app/(anon)/signin/page.module.css
  app/(anon)/signin/page.tsx
  app/(anon)/signup/page.module.css
  app/(anon)/signup/page.tsx
  app/components/Avatar.tsx
  app/layout.tsx
  app/shared-page-layout.css
  backend/infrastructure/repositories/SbUserRepository.ts
  package-lock.json
  package.json
Labels: enhancement

#89 Feat: #88 채팅방 UI 리디자인 및 메시지 렌더링 최적화
  app/(anon)/chatrooms/[id]/components/ChatInput.module.css
  app/(anon)/chatrooms/[id]/components/ChatInput.tsx
  app/(anon)/chatrooms/[id]/components/ChatLog.module.css
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/chatrooms/[id]/components/ChatSearch.module.css
  app/(anon)/chatrooms/[id]/components/ChatSearch.tsx
  app/(anon)/chatrooms/[id]/page.module.css
  app/(anon)/chatrooms/[id]/page.tsx
  app/api/chat/logs/route.ts
  app/api/chat/search/route.ts
Labels: bug, documentation

#91 feat/#90-cities 데이터 불러오기 및 경로 설정
  app/(anon)/cities/[id]/layout.tsx
  app/(anon)/cities/[id]/page.tsx
  app/(anon)/cities/page.tsx
  app/api/tour/route.ts
  app/components/Header.tsx
  app/components/header.module.css
  package-lock.json
  package.json
Labels: bug, documentation

#94 Fix/chat reply
  app/(anon)/chatrooms/[id]/components/ChatInput.module.css
  app/(anon)/chatrooms/[id]/components/ChatLog.module.css
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/chatrooms/[id]/components/ChatReply.module.css
  app/(anon)/chatrooms/[id]/components/ChatReply.tsx
  app/(anon)/chatrooms/[id]/components/ChatSearch.module.css
  app/(anon)/chatrooms/[id]/components/ChatSearch.tsx
  app/(anon)/chatrooms/[id]/page.module.css
  app/(anon)/chatrooms/[id]/page.tsx
  app/(anon)/cities/[id]/page.tsx
  app/api/chat/logs/route.ts
  app/api/chat/search/route.ts
  backend/application/chats/usecases/SearchByChatUseCase.ts
  backend/infrastructure/repositories/SbChatLogRepository.ts
  backend/infrastructure/repositories/SbChatRepository.ts
  backend/infrastructure/repositories/SbTagRepository.ts
Labels: bug

#95 feat: #82 공통 컴포넌트 로딩 스피너 추가
  app/(anon)/me/chats/components/EmptyChatList.tsx
  app/(anon)/me/chats/components/empty-chat-list.module.css
  app/(anon)/me/chats/page.module.css
  app/(anon)/me/chats/page.tsx
  app/(anon)/me/page.module.css
  app/api/user/chats/route.ts
  app/components/LoadingSpinner.tsx
  app/components/loading.module.css
  app/hooks/useGetCurrentUserChatList.ts
  app/hooks/useGetCurrentUserChats.ts
  app/types/ApiResponse.ts
  backend/application/chats/dtos/GetChatListRequestDto.ts
  backend/application/chats/dtos/GetChatListResponseDto.ts
  backend/application/chats/usecases/GetChatListByUserIdUsecase.ts
  backend/application/chats/usecases/GetCurrentUserChatListUsecase.ts
  backend/domain/repositories/ChatRepository.ts
  backend/infrastructure/repositories/SbChatRepository.ts
  backend/infrastructure/repositories/SbUserRepository.ts
  config/auth.ts
  package-lock.json
  package.json
Labels: enhancement

#102 [feat] 채팅방 UI 리팩토링 및 기능 개선 (태그, 댓글, 참여인원, 시간 등)Feature/show top tag
  app/(anon)/chatrooms/[id]/components/ChatInput.module.css
  app/(anon)/chatrooms/[id]/components/ChatInput.tsx
  app/(anon)/chatrooms/[id]/components/ChatLog.module.css
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/chatrooms/[id]/components/ChatReply.tsx
  app/(anon)/chatrooms/[id]/components/ChatRoomInfo.module.css
  app/(anon)/chatrooms/[id]/components/ChatRoomInfo.tsx
  app/(anon)/chatrooms/[id]/components/ChatSearch.module.css
  app/(anon)/chatrooms/[id]/components/TopTagList.module.css
  app/(anon)/chatrooms/[id]/components/TopTagList.tsx
  app/(anon)/chatrooms/[id]/page.module.css
  app/(anon)/chatrooms/[id]/page.tsx
  app/(anon)/chatrooms/[id]/types.ts
  app/api/chat/rooms/route.ts
  app/api/chat/search/route.ts
  app/api/chat/top-tags/route.ts
  app/stores/useCitystore.ts
  backend/application/top-tags/dtos/TopTagResponseDTO.ts
  backend/application/top-tags/usecases/GetTopTagsByRoomId.ts
  backend/domain/entities/Tag.ts
  backend/domain/repositories/TopTagRepository.ts
  backend/infrastructure/repositories/SbChatRepository.ts
  backend/infrastructure/repositories/SbTagRepository.ts
  backend/infrastructure/repositories/SbTopTagRepository.ts
Labels: bug, documentation, enhancement

#103 Feature/82 mypage
  app/(anon)/me/account/components/NicknameChangeModal.tsx
  app/(anon)/me/account/components/PasswordChangeModal.tsx
  app/(anon)/me/account/page.module.css
  app/(anon)/me/account/page.tsx
  app/(anon)/me/chats/components/EmptyChatList.tsx
  app/(anon)/me/chats/page.tsx
  app/components/Header.tsx
  app/components/Modal.module.css
  app/components/Modal.tsx
  backend/infrastructure/repositories/SbChatRepository.ts
Labels: enhancement

#107 Feature/82 mypage
  app/(anon)/me/account/components/NicknameChangeModal.tsx
  app/(anon)/me/account/components/PasswordChangeModal.tsx
  app/(anon)/me/account/page.tsx
  app/api/users/me/route.ts
  app/apis/authApi.ts
  app/hooks/useGetCurrentUserChats.ts
  app/hooks/useSignin.ts
  app/hooks/useSignout.ts
  app/hooks/useSignup.ts
  app/hooks/useUpdateUser.ts
  backend/application/auth/usecases/SigninUsecase.ts
  backend/application/users/dtos/UpdateUserRequestDto.ts
  backend/application/users/dtos/UpdateUserResponseDto.ts
  backend/application/users/usecases/SignupUsecase.ts
  backend/application/users/usecases/UpdateUserUsecase.ts
  backend/domain/repositories/UserRepository.ts
  backend/infrastructure/repositories/SbUserRepository.ts
  config/auth.ts
Labels: enhancement

#108 Feat : #106 cities/[id] 에 인기태그 컴포넌트 연결
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/chatrooms/[id]/page.tsx
  app/(anon)/cities/[id]/page.tsx
  app/components/TopTagList.module.css
  app/components/TopTagList.tsx
Labels: documentation

#110 style/#24- tagList 추가로 인한 CSS 수정
  app/(anon)/cities/[id]/components/categoryFilter.module.css
  app/(anon)/cities/[id]/components/chatButton.module.css
  app/(anon)/cities/[id]/layout.tsx
  app/(anon)/cities/[id]/page.tsx
  app/api/cities/route.ts
Labels: documentation

#111 Feature/105 UI
  app/(anon)/signin/page.module.css
  app/(anon)/signin/page.tsx
  app/(anon)/signup/page.module.css
  app/(anon)/signup/page.tsx
  app/SharedPageLayout.tsx
  app/shared-page-layout.css
Labels: enhancement

#113 fix: #112 replyToId 타입 오류로 인한 실시간 답글 UI 미렌더링 문제 해결
  app/(anon)/chatrooms/[id]/components/AdaptChatFromSupabase.ts
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/chatrooms/[id]/page.tsx
  app/(anon)/cities/[id]/page.tsx
  app/(anon)/me/chats/components/EmptyChatList.tsx
  app/(anon)/me/chats/components/empty-chat-list.module.css
  app/(anon)/me/chats/page.tsx
  app/(anon)/me/page.module.css
Labels: bug, documentation

#114 feat: #105 페이지별 배경 동적 이미지 경로 구현
  app/(anon)/cities/[id]/page.tsx
  app/SharedPageLayout.tsx
  app/components/Header.tsx
  app/shared-page-layout.css
  app/stores/useCitystore.ts
Labels: enhancement

#119 fix : cities css 최종수정
  app/(anon)/cities/[id]/components/ChatButton.tsx
  app/(anon)/cities/[id]/components/categoryFilter.module.css
  app/(anon)/cities/[id]/components/chatButton.module.css
  app/(anon)/cities/[id]/components/tourCard.module.css
  app/(anon)/cities/[id]/page.tsx
  app/components/subSlider.module.css
Labels: bug

#121 fix: 지역 필터링 배열 정렬 시, 타입 오류 해결
  app/(anon)/me/chats/page.tsx
Labels: bug

#122 fix: eslint error 수정
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/chatrooms/[id]/page.tsx
  app/(anon)/me/account/components/NicknameChangeModal.tsx
  app/(anon)/me/account/components/PasswordChangeModal.tsx
  app/(anon)/signin/page.tsx
  app/(anon)/signup/components/DuplicateField.tsx
  app/(anon)/signup/components/FormField.tsx
  app/(anon)/signup/page.tsx
  app/components/Footer.tsx
Labels: bug

#123 release : merge develop into main v1.2.2
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/chatrooms/[id]/page.tsx
  app/(anon)/me/account/components/NicknameChangeModal.tsx
  app/(anon)/me/account/components/PasswordChangeModal.tsx
  app/(anon)/signin/page.tsx
  app/(anon)/signup/components/DuplicateField.tsx
  app/(anon)/signup/components/FormField.tsx
  app/(anon)/signup/page.tsx
  app/components/Footer.tsx
Labels: bug

#124 Fix : cities/[id]와 cityStore의 type 중복 선언으로 인한 오류 해결
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/cities/[id]/page.tsx
  app/stores/useCitystore.ts
Labels: bug

#125 release : merge develop into main v1.2.3
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
  app/(anon)/cities/[id]/page.tsx
  app/stores/useCitystore.ts
Labels: bug

#126 fix: pr 충돌로 인한 formatted time 로직 중복 코드 제거
  app/(anon)/chatrooms/[id]/components/ChatLog.tsx
Labels: bug

#128 fix : chatButton type 선언 오류 해결
  app/(anon)/cities/[id]/components/ChatButton.tsx
Labels: bug

#129 release : merge develop into main v1.2.5
  app/(anon)/cities/[id]/components/ChatButton.tsx
Labels: bug

#133 fix: change unused navigation url
  app/components/Header.tsx
Labels: bug
